/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  static connect(): Client
  listDeployments(): Promise<Array<Deployment>>
}

export declare class Deployment {
  containerId: string
  creationSource?: CreationSource
}

export declare const enum CreationSource {
  AtlasCLI = 0,
}
